ballena-io/ballena-uikit

- src/widgets/Menu/config.ts
Add our links to Telegram and Twitter
> refactor: Add footer links

- package.json
> ci: Bump version 0.15.2

- package.json
- src/__tests__/components/alert.test.tsx
- src/__tests__/components/button.test.tsx
- src/__tests__/components/buttonmenu.test.tsx
- src/__tests__/components/card.test.tsx
- src/__tests__/components/checkbox.test.tsx
- src/__tests__/components/dropdown.test.tsx
- src/__tests__/components/fallingbunnies.test.tsx
- src/__tests__/components/heading.test.tsx
- src/__tests__/components/input.test.tsx
- src/__tests__/components/link.test.tsx
- src/__tests__/components/notificationdot.test.tsx
- src/__tests__/components/progress.test.tsx
- src/__tests__/components/radio.test.tsx
- src/__tests__/components/skeleton.test.tsx
- src/__tests__/components/spinner.test.tsx
- src/__tests__/components/svg.test.tsx
- src/__tests__/components/tag.test.tsx
- src/__tests__/components/text.test.tsx
- src/__tests__/components/toggle.test.tsx
- src/__tests__/widgets/menu.test.tsx
- src/__tests__/widgets/modal.test.tsx
- src/__tests__/widgets/walletModal.test.tsx
- src/components/Toggle/StyledToggle.tsx
- src/components/Toggle/theme.ts
- src/theme/colors.ts
- src/theme/types.ts
Add our branding colors + some toogle styles
> Feat: Update palette colors

- package.json
> ci: Bump to v0.15.3

- src/__tests__/components/fallingbunnies.test.tsx
- src/__tests__/widgets/menu.test.tsx
- src/components/Svg/Icons/Logo.tsx
- src/widgets/Menu/components/Logo.tsx
- src/widgets/Menu/icons/Logo.tsx
> Fix: Logos sizes

- package.json
- src/widgets/Menu/components/CakePrice.tsx
- Update ballena logoRound
- Update link to Balle price
- Bump version to 0.15.5
> Feat: Add price token

- package.json
> chore: Bump version to 0.15.6

- .storybook/preview-head.html
- src/ResetCSS.tsx
- src/__tests__/components/heading.test.tsx
- src/__tests__/widgets/modal.test.tsx
- src/__tests__/widgets/walletModal.test.tsx
- src/components/Heading/Heading.tsx
Update Heading font to 'Dosis'
Update body font to 'Roboto'
> feat: Update fonts

- src/__tests__/widgets/menu.test.tsx
- src/widgets/Menu/Menu.tsx
- src/widgets/Menu/components/Panel.tsx
Reverts ballena-io/ballena-uikit#11
> Revert "refactor: Top bar always visible"

- package.json
> build: Bump to 0.15.7

- package.json
- src/__tests__/widgets/menu.test.tsx
- src/widgets/Menu/components/UserBlock.tsx
- Change Account button styles
- Bump version to 0.16.0
- Update snapshots
> Refactor: Polish account button

- src/__tests__/widgets/menu.test.tsx
- src/widgets/Menu/components/PanelBody.tsx
- src/widgets/Menu/config.ts
- src/widgets/Menu/types.ts
Now config menu can add external boolean to open links in another window.
> feat: Add external links to menu items

- src/__tests__/widgets/menu.test.tsx
- src/widgets/Menu/Menu.tsx
- src/widgets/Menu/components/BallePrice.tsx
- src/widgets/Menu/index.stories.tsx
- src/widgets/Menu/types.ts
Add ballePriceUsd to top bar, we still need to add the link to the contract when we deploy
> feat: Add ballePriceUsd

- package.json
> build: Bump version to 0.16.2

- src/__tests__/widgets/walletModal.test.tsx
- src/widgets/WalletModal/ConnectModal.tsx
Add our own link to 'How to connect'
> refactor: Add balle doc link

- package.json
> chore: Bump version to 0.16.3

- src/__tests__/components/balanceInput.test.tsx
- src/components/BalanceInput/BalanceInput.tsx
- src/components/BalanceInput/index.stories.tsx
- src/components/BalanceInput/index.tsx
- src/components/BalanceInput/styles.tsx
- src/components/BalanceInput/types.ts
> feat: Add BalanceInput

- package.json
> build: Bump to 0.17.0

- package.json
- src/index.ts
> fix: Add export BalanceInput

- package.json
- src/__tests__/components/checkbox.test.tsx
- src/__tests__/components/notificationdot.test.tsx
- src/__tests__/components/radio.test.tsx
- src/__tests__/components/toggle.test.tsx
- src/components/Toggle/StyledToggle.tsx
- src/theme/colors.ts
- src/widgets/Toast/Toast.tsx
Toast revamp
Bump version to 0.18.0
> Refactor: Toasts + Bump version to 0.18.0

- package.json
> chore: Bump version to 0.19.0

- package.json
- src/__tests__/widgets/menu.test.tsx
- src/widgets/Menu/components/BallePrice.tsx
Add balle price link
bump version to 0.20.0
> Feat: Ballev2 price link

- src/__tests__/widgets/menu.test.tsx
- src/widgets/Menu/components/Logo.tsx
feat: Remove logo mobile version
> feat: Remove logo mobile version

- package.json
> chore: Bump version 0.21.0

- package.json
- src/__tests__/components/balanceInput.test.tsx
- src/components/BalanceInput/styles.tsx
Hide balance input arrows
Bump version to 0.22.0
> Refactor: Hide balance input arrows

- package.json
- src/__tests__/widgets/menu.test.tsx
- src/widgets/Menu/components/Accordion.tsx
- src/widgets/Menu/components/MenuEntry.tsx
- src/widgets/Menu/config.ts
- src/widgets/Menu/icons/Verified.tsx
- src/widgets/Menu/icons/index.ts
- Add verified icon to Menu icons
- Add dropdown menu item
- Bump version to 0.23.0
> Feat: Add dropdown menu item

- package.json
> feat: Change registry, bump version
